<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://loanapprover.soacourse.unsw.edu.au/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns3="http://schemas.xmlsoap.org/soap/http"
	xmlns:ns1="http://soacourse.unsw.edu.au/loanapprover" name="LoanApprovalPTImplService"
	targetNamespace="http://loanapprover.soacourse.unsw.edu.au/">
	<wsdl:import
		location="loanapprover.wsdl"
		namespace="http://soacourse.unsw.edu.au/loanapprover">
	</wsdl:import>
	<wsdl:binding name="LoanApprovalPTImplServiceSoapBinding"
		type="ns1:loanApprovalPT">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="approve">
			<soap:operation soapAction="http://soacourse.unsw.edu.au/loanapprover/approve"
				style="document" />
			<wsdl:input name="approve">
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output name="approveResponse">
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="LoanApprovalPTImplService">
		<wsdl:port binding="tns:LoanApprovalPTImplServiceSoapBinding"
			name="LoanApprovalPTImplPort">
			<soap:address
				location="http://localhost:8080/LoanApproverServiceT2/loanapprover" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>